// client/src/components/Record/RecordLabel.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

export interface RecordLabelProps {
  value: string;
  anchor?: string;
  onClick?: () => void;
}

export default function RecordLabel(props: RecordLabelProps) {
  return (
    <>
      <p className="group text-2xl font-bold my-2">
        <a
          className="text-gray-900 dark:text-white"
          // name={props.section}
          href={props.anchor ? `#${props.anchor}` : undefined}
          onClick={props.onClick}
        >
          {props.value}
        </a>
        <FontAwesomeIcon
          icon="link"
          className="ml-2 text-gray-600 dark:text-gray-400 invisible group-hover:visible"
        />
      </p>
    </>
  );
}

// lets-svelte-it/src/components/NavBar/Record/RecordLabel.svelte
<script lang="ts">
  import { SectionFormat } from "../../../lib/string";

  export let label: string;

  const name = SectionFormat(label);
</script>

<p class="group text-2xl font-bold my-2">
  <a {name} class="text-gray-900 dark:text-white" href="#{name}">{label}</a>
  <i
    class="fas fa-link text-gray-600 dark:text-gray-400 invisible group-hover:visible"
  />
</p>

<style></style>
